kind: Deployment
apiVersion: apps/v1
metadata: 
  name: deployment-payment

spec:
  replicas: 2
  selector:
    matchLabels:
      service: payment

  template:
    metadata:
      labels:
        service: payment

    spec:
      containers:
        - name: v1
          image: manishramdhave/payment:1.0
          ports:
            - containerPort: 8080
